"""initial migratetion

Revision ID: 4414fe89601b
Revises: 
Create Date: 2017-03-01 16:00:42.072624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4414fe89601b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passwor_hash', sa.Unicode(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'passwor_hash')
    # ### end Alembic commands ###
